replicaCount: 1
image:
  repository: localhost:5001/lw-idp/sample-nginx
  tag: be4f725
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  host: sample.lw-idp.local
resources:
  requests: { cpu: 50m, memory: 32Mi }
  limits:   { cpu: 200m, memory: 128Mi }
